#title: Your Name - Future-Ready Professional
#description: Showcasing your skills and experience in a cutting-edge way.
# base_url: / (Optional, if your website is not at the root of your repository)
url: https://zzulfaqar.github.io/Faqar.git.io/ 

theme: jekyll-theme-minimal
title: Muhd Zulfaqar
logo: /images/profile-circle.jpg
#show_downloads: true
description: Welcome to my simple portfolio website

collections:
  pages:
    output: true

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-assets 

# Additional configurations specific to your chosen theme